# Generated by Django 3.2.23 on 2024-02-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftmanager',
            name='user',
        ),
    ]
