# Generated by Django 3.2.23 on 2024-02-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0004_auto_20240218_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='monthlyroster',
            name='work_day',
        ),
        migrations.AlterField(
            model_name='monthlyroster',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffcalendar.shifttype'),
        ),
        migrations.DeleteModel(
            name='ShiftManager',
        ),
    ]
