# Generated by Django 3.2.23 on 2024-02-21 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0005_auto_20240218_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyroster',
            options={'verbose_name': "Employees' roster"},
        ),
        migrations.AddField(
            model_name='monthlyroster',
            name='work_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=datetime.datetime(2024, 2, 21, 15, 16, 28, 178780, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
