# Generated by Django 3.2.23 on 2024-02-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0007_auto_20240221_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_symbol', models.CharField(max_length=10)),
                ('day_code', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-day_code'],
            },
        ),
        migrations.RemoveField(
            model_name='monthlyroster',
            name='work_day',
        ),
        migrations.AddField(
            model_name='monthlyroster',
            name='work_days',
            field=models.ManyToManyField(to='staffcalendar.WorkDay'),
        ),
    ]
