# Generated by Django 3.2.23 on 2024-02-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0007_auto_20240221_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyroster',
            name='employees',
        ),
    ]
