# Generated by Django 3.2.23 on 2024-02-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0008_remove_monthlyroster_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyroster',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffcalendar.shifttype'),
        ),
    ]
