# Generated by Django 3.2.23 on 2024-02-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0008_auto_20240221_2022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together={('day_symbol', 'day_code')},
        ),
    ]
