# Generated by Django 3.2.23 on 2024-02-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0009_alter_workday_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workday',
            options={'ordering': ['day_code']},
        ),
    ]
