# Generated by Django 3.2.23 on 2024-02-22 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0010_alter_workday_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyroster',
            name='description',
            field=models.CharField(default=datetime.datetime(2024, 2, 22, 13, 1, 13, 987029, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
