# Generated by Django 3.2.23 on 2024-03-05 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20240305_1820'),
        ('staffcalendar', '0011_monthlyroster_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyroster',
            name='description',
        ),
        migrations.RemoveField(
            model_name='monthlyroster',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='monthlyroster',
            name='week_no',
        ),
        migrations.AddField(
            model_name='monthlyroster',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='users.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyroster',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 5, 17, 31, 53, 140718, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='monthlyroster',
            name='work_days',
        ),
        migrations.AddField(
            model_name='monthlyroster',
            name='work_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffcalendar.workday'),
        ),
    ]
