# Generated by Django 3.2.23 on 2024-02-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0011_monthlyroster_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyroster',
            name='shift',
        ),
        migrations.AddField(
            model_name='monthlyroster',
            name='shift',
            field=models.ManyToManyField(to='staffcalendar.ShiftType'),
        ),
    ]
