# Generated by Django 3.2.23 on 2024-02-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0012_auto_20240226_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyroster',
            old_name='shift',
            new_name='shifts',
        ),
    ]
