# Generated by Django 3.2.23 on 2024-03-06 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_bacth_userprofile_batch'),
        ('staffcalendar', '0013_alter_monthlyroster_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyroster',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='users.batch'),
        ),
    ]
