# Generated by Django 3.2.23 on 2024-03-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0015_auto_20240306_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyroster',
            unique_together={('shift_date', 'work_day', 'shift')},
        ),
    ]
