# Generated by Django 3.2.23 on 2024-03-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_bacth_userprofile_batch'),
        ('staffcalendar', '0016_alter_monthlyroster_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyroster',
            unique_together={('shift_date', 'work_day', 'shift', 'batch')},
        ),
    ]
