# Generated by Django 3.2.23 on 2024-03-21 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0017_alter_monthlyroster_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyroster',
            old_name='shift_date',
            new_name='shift_end_date',
        ),
        migrations.AddField(
            model_name='monthlyroster',
            name='shift_start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 17, 33, 37, 634025, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='monthlyroster',
            unique_together=set(),
        ),
    ]
