# Generated by Django 3.2.23 on 2024-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0018_auto_20240321_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='duration',
            field=models.PositiveSmallIntegerField(default=24),
            preserve_default=False,
        ),
    ]
