# Generated by Django 3.2.23 on 2024-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0019_shifttype_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='day_code',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='day_symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
