# Generated by Django 3.2.23 on 2024-01-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeebatchupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reader_uid',
            field=models.CharField(default='DUMMY_<function generate_uid at 0x7fbe81487c40>', max_length=128, unique=True),
        ),
    ]
