# Generated by Django 3.2.23 on 2024-01-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_reader_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reader_uid',
            field=models.CharField(default='DUMMY_IDCKF1HLZN', max_length=128, unique=True),
        ),
    ]
