# Generated by Django 3.2.23 on 2024-01-31 23:09

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_reader_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reader_uid',
            field=models.CharField(default=utils.utils.dummy_unique_str, max_length=128, unique=True),
        ),
    ]
