# Generated by Django 3.2.23 on 2024-02-15 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffcalendar', '0002_remove_shiftmanager_user'),
        ('users', '0005_alter_userprofile_reader_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffcalendar.shiftmanager'),
        ),
    ]
