# Generated by Django 3.2.23 on 2024-02-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shift',
        ),
    ]
