# Generated by Django 3.2.23 on 2024-02-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240227_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecategory',
            old_name='allowed_meal_access',
            new_name='drink_access',
        ),
        migrations.AddField(
            model_name='employeecategory',
            name='meal_access',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
