# Generated by Django 3.2.23 on 2024-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240227_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employeecategory',
            options={'verbose_name_plural': "Employees' categories"},
        ),
    ]
