# Generated by Django 3.2.23 on 2024-02-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': "Employees' status",
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employeestatus'),
        ),
    ]
