# Generated by Django 3.2.23 on 2024-02-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20240227_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatus',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
