# Generated by Django 3.2.23 on 2024-02-28 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_employeestatus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default=datetime.datetime(2024, 2, 28, 12, 3, 26, 259765, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
