# Generated by Django 3.2.23 on 2024-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(default='123456', max_length=128,),
            preserve_default=False,
        ),
    ]
