# Generated by Django 3.2.23 on 2024-03-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='staff_status',
            new_name='employee_status',
        ),
    ]
