# Generated by Django 3.2.23 on 2024-03-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20240305_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='group',
            new_name='bacth',
        ),
    ]
