# Generated by Django 3.2.23 on 2024-03-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_group_userprofile_bacth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bacth',
            new_name='batch',
        ),
    ]
