# Generated by Django 3.2.23 on 2024-03-25 15:12

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=utils.utils.dummy_email, max_length=255, unique=True),
        ),
    ]
