# Generated by Django 3.2.23 on 2024-03-25 15:42

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reader_uid',
            field=models.CharField(default=utils.utils.dummy_unique_str, max_length=128),
        ),
    ]
