# Generated by Django 3.2.23 on 2024-04-04 01:01

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20240326_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeebatchupload',
            options={'verbose_name_plural': 'Batch File Upload'},
        ),
        migrations.AlterModelOptions(
            name='employeecategory',
            options={'verbose_name_plural': "Employees' Categories"},
        ),
        migrations.AlterModelOptions(
            name='employeestatus',
            options={'verbose_name_plural': "Employees' Status"},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='employeecategory',
            name='cat_name',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='status',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reader_uid',
            field=models.CharField(default=utils.utils.dummy_unique_str, max_length=155, unique=True),
        ),
    ]
