# Generated by Django 3.2.23 on 2024-01-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='door',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
