# Generated by Django 3.2.23 on 2024-02-20 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reporttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 20, 10, 35, 42, 868339, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporttype',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
