# Generated by Django 3.2.23 on 2024-03-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_drinkcategory_drinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name_plural': 'Drinks'},
        ),
        migrations.AlterModelOptions(
            name='drinkcategory',
            options={'verbose_name_plural': 'Drinks Categories'},
        ),
    ]
