# Generated by Django 3.2.23 on 2024-03-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240305_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkcategory',
            options={'verbose_name_plural': 'Drink Categories'},
        ),
    ]
