# Generated by Django 3.2.23 on 2024-03-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_drinkcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('order_date', models.DateTimeField()),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.drink')),
                ('transaction_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
    ]
