# Generated by Django 3.2.23 on 2024-03-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_drinkcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkcart',
            name='reader_uid',
            field=models.CharField(default='123456', max_length=25),
            preserve_default=False,
        ),
    ]
