# Generated by Django 3.2.23 on 2024-03-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_drinkcart_reader_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkcart',
            old_name='transaction_no',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='drinkcart',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
