# Generated by Django 3.2.23 on 2024-03-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transaction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='drinkcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
