# Generated by Django 3.2.23 on 2024-04-04 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240326_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkcart',
            options={'verbose_name_plural': 'Drinks Carts'},
        ),
    ]
