# Generated by Django 3.2.23 on 2024-04-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_drinkcart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='drinkcategory',
            name='name',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='access_point',
            field=models.CharField(max_length=125),
        ),
    ]
