# Generated by Django 3.2.23 on 2024-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20240404_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
